services:
  mysql:
    image: mysql:8.4
    restart: always
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../moftaked-server-express
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../moftaked-server-express:/app
      - /app/node_modules
    env_file:
      - ../moftaked-server-express/.env.docker
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default

volumes:
  mysql_data:
